apiVersion: v1 
kind: Pod
metadata:
  name: busyboxtest
spec:
  nodeSelector:
    kubernetes.io/os: windows
  containers:
  - name: busyboxtestcontainer
    image: registry.k8s.io/e2e-test-images/busybox:1.29-4
    terminationMessagePath: "/dev/termination-custom-log"
    command: ["/bin/sh", "-c"]
    args: ["/bin/echo -n Done > /dev/termination-custom-log"]
    securityContext:
      windowsOptions:
        runAsUserName: "ContainerUser"
  restartPolicy: Never
