---
kind: Pod
apiVersion: v1
metadata:
  name: pod-azuredisk
spec:
  containers:
    - image: mcr.microsoft.com/oss/kubernetes/pause:3.9-hotfix-20230808 
      imagePullPolicy: IfNotPresent
      command:
        - pause.exe    
      name: pod-azuredisk
      volumeMounts:
        - name: disk01
          mountPath: 'c:\data'
  nodeSelector:
    kubernetes.io/os: windows
  volumes:
    - name: disk01
      persistentVolumeClaim:
        claimName: azure-managed-disk 
